[package]
name = "sheet"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
bevy-inspector-egui = { version = "0.18" }