[package]
name = "sheet"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
rand = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
bevy-inspector-egui = { version = "0.23" }
common = { path = "../common", version = "0.1" }